[versions]
appcompat = "1.6.1"
constraintlayout = "2.1.4"
activity = "1.8.2"
material = "1.11.0"
room = "2.6.1"
junit = "4.13.2"
espresso = "3.5.1"
extJunit = "1.1.5"
mockito = "5.2.0"
robolectric = "4.11.1"
mpandroidchart = "3.1.0"
work = "2.8.0"
lottie = "6.0.0"
relay = "0.3.12"
places = "3.4.0"

[libraries]
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
activity = { module = "androidx.activity:activity", version.ref = "activity" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
room-common = { module = "androidx.room:room-common", version.ref = "room" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
databinding-adapters = { module = "androidx.databinding:databinding-adapters", version = "8.3.0" }
places = { module = "com.google.android.libraries.places:places", version.ref = "places" }
espresso-contrib = { module = "androidx.test.espresso:espresso-contrib", version.ref = "espresso" }
work-testing = { module = "androidx.work:work-testing", version.ref = "work" }
rules = { module = "androidx.test:rules", version = "1.5.0" }
espresso-intents = { module = "androidx.test.espresso:espresso-intents", version.ref = "espresso" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-android = { module = "org.mockito:mockito-android", version.ref = "mockito" }
mockito-inline = { module = "org.mockito:mockito-inline", version.ref = "mockito" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
junit = { module = "junit:junit", version.ref = "junit" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
ext-junit = { module = "androidx.test.ext:junit", version.ref = "extJunit" }
mpandroidchart = { module = "com.github.PhilJay:MPAndroidChart", version.ref = "mpandroidchart" }
work-runtime = { module = "androidx.work:work-runtime", version.ref = "work" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }

[plugins]
android-application = { id = "com.android.application", version = "8.6.1" }
relay = { id = "com.google.relay", version.ref = "relay" }